USE MASTER
GO

CREATE DATABASE PROIV
ON PRIMARY
(NAME = 'PROIV', FILENAME = 'C:\data\PROIV.mfd',
size=1000MB, FILEGROWTH=25%)
LOG ON
(NAME = 'PROIVLOG', FILENAME = 'C:\data\PROIVLOG.ldf',
size=500MB, FILEGROWTH=25%)
GO
