/* CREACION DE BASE DE DATOS */
USE MASTER
GO

CREATE DATABASE PROIV
ON PRIMARY (NAME = 'PROIV', FILENAME = 'C:\data\PROIV.mfd', size=1000MB, FILEGROWTH=25%)
LOG ON (NAME = 'PROIVLOG', FILENAME = 'C:\data\PROIVLOG.ldf', size=500MB, FILEGROWTH=25%)
GO

USE PROIV
GO

/* CREACION DE TABLAS */
CREATE TABLE EXTRAS (IDEXTRA INT,
		     NOMBREEXTRA VARCHAR(50),
		     PRECIOEXTRA MONEY
		     PRIMARY KEY (IDEXTRA)
);

CREATE TABLE CATEGORIAS (IDCATEGORIA INT,
			 NOMBRECATEGORIA VARCHAR(50),
			 DESCRIPCION VARCHAR(50)
			 PRIMARY KEY (IDCATEGORIA)
);

CREATE TABLE PRODUCTOS (IDPRODUCTO INT,
		  	NOMBREPRODUCTO VARCHAR(40),
			PRECIOPRODUCTO MONEY,
			CANTIDADVENTAS INT,
			IDEXTRA INT,
			IDCATEGORIA INT,
			PRIMARY KEY (IDPRODUCTO),
			FOREIGN KEY (IDEXTRA) REFERENCES EXTRAS(IDEXTRA),
			FOREIGN KEY (IDCATEGORIA) REFERENCES CATEGORIAS(IDCATEGORIA)
);

CREATE TABLE MESEROS (IDMESERO INT,
		      NOMBEMESERO VARCHAR(50),
		      PRIMARY KEY (IDMESERO)
);

CREATE TABLE ORDENES (IDORDEN INT,
		      NOMBREORDEN VARCHAR(50),
		      CANTIDADPRODUCTOS INT,
		      IDPRODUCTO INT,
		      IDMESERO INT,
		      PRIMARY KEY (IDORDEN),
		      FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTOS(IDPRODUCTO),
		      FOREIGN KEY (IDMESERO) REFERENCES MESEROS(IDMESERO)
);

CREATE TABLE MESAS (IDMESA INT,
		    CAPACIDAD INT,
		    ESTADO VARCHAR(20),
		    IDORDEN INT,
		    PRIMARY KEY (IDMESA),
		    FOREIGN KEY (IDORDEN) REFERENCES ORDENES(IDORDEN)
);

CREATE TABLE FACTURAS (IDFACTURA INT,
		       PRECIOUNIDAD MONEY,
		       PRECIOTOTAL MONEY,
		       METODOPAGO VARCHAR(20),
		       MENSAJE VARCHAR(60),
		       NOMBRECAJERO VARCHAR(50),
		       TOTALCANCELADO MONEY,
		       VUELTO AS PRECIOTOTAL-TOTALCANCELADO,
		       FECHA DATE,
		       IDORDEN INT,
	               PRIMARY KEY (IDFACTURA),
		       FOREIGN KEY (IDORDEN) REFERENCES ORDENES(IDORDEN)
);
