/*TABLA EXTRAS*/CREATE TABLE EXTRAS (IDEXTRA INT,
					NOMBREEXTRA VARCHAR(50),
					PRECIOEXTRA MONEY
					PRIMARY KEY (IDEXTRA));
/*TABLA CATEGORIAS*/
CREATE TABLE CATEGORIAS (IDCATEGORIA INT,
						NOMBRECATEGORIA VARCHAR(50),
						DESCRIPCION VARCHAR(50)
						PRIMARY KEY (IDCATEGORIA));
/*TABLA PRODUCTOS*/
CREATE TABLE PRODUCTOS (IDPRODUCTO INT,
						NOMBREPRODUCTO VARCHAR(40),
						PRECIOPRODUCTO MONEY,
						CANTIDADVENTAS INT,
						IDEXTRA INT,
						IDCATEGORIA INT,
						PRIMARY KEY (IDPRODUCTO),
						FOREIGN KEY (IDEXTRA) REFERENCES EXTRAS(IDEXTRA),
						FOREIGN KEY (IDCATEGORIA) REFERENCES CATEGORIAS(IDCATEGORIA));
/*TABLA MESERO*/
CREATE TABLE MESEROS (IDMESERO INT,
					  NOMBEMESERO VARCHAR(50),
					  PRIMARY KEY (IDMESERO));

/*TABLA ORDENES*/
CREATE TABLE ORDENES (IDORDEN INT,
					  NOMBREORDEN VARCHAR(50),
					  CANTIDADPRODUCTOS INT,
					  IDPRODUCTO INT,
					  IDMESERO INT,
					  PRIMARY KEY (IDORDEN),
					  FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTOS(IDPRODUCTO),
					  FOREIGN KEY (IDMESERO) REFERENCES MESEROS(IDMESERO));
/*TABLA MESAS*/
CREATE TABLE MESAS (IDMESA INT,
					CAPACIDAD INT,
					ESTADO VARCHAR(20),
					IDORDEN INT,
					PRIMARY KEY (IDMESA),
					FOREIGN KEY (IDORDEN) REFERENCES ORDENES(IDORDEN));
/*TABLA FACTURAS*/
CREATE TABLE FACTURAS (IDFACTURA INT,
					   PRECIOUNIDAD MONEY,
					   PRECIOTOTAL MONEY,
					   METODOPAGO VARCHAR(20),
					   MENSAJE VARCHAR(60),
					   NOMBRECAJERO VARCHAR(50),
					   TOTALCANCELADO MONEY,
					   VUELTO AS PRECIOTOTAL-TOTALCANCELADO,
					   FECHA DATE,
					   IDORDEN INT,
					   PRIMARY KEY (IDFACTURA),
					   FOREIGN KEY (IDORDEN) REFERENCES ORDENES(IDORDEN));