//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA
    {
        public int ID_FACTURA { get; set; }
        public Nullable<decimal> PRECIO_UNIDAD { get; set; }
        public Nullable<decimal> PRECIO_TOTAL { get; set; }
        public string METODO_PAGO { get; set; }
        public string MENSAJE { get; set; }
        public string NOMBRE_CAJERO { get; set; }
        public Nullable<decimal> TOTAL_CANCELADO { get; set; }
        public Nullable<decimal> VUELTO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<int> ID_ORDEN { get; set; }
    
        public virtual ORDENE ORDENE { get; set; }
    }
}
