//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDENE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDENE()
        {
            this.FACTURAS = new HashSet<FACTURA>();
            this.PRODUCTO_X_ORDEN = new HashSet<PRODUCTO_X_ORDEN>();
        }
    
        public int ID_ORDEN { get; set; }
        public string NOMBRE_ORDEN { get; set; }
        public Nullable<int> ID_MESERO { get; set; }
        public Nullable<int> ID_MESA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURA> FACTURAS { get; set; }
        public virtual MESA MESA { get; set; }
        public virtual MESERO MESERO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTO_X_ORDEN> PRODUCTO_X_ORDEN { get; set; }
    }
}
