//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO_X_ORDEN
    {
        public int ID_PRODUCTO { get; set; }
        public int ID_ORDEN { get; set; }
        public int CANTIDAD_PRODUCTO { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual ORDENE ORDENE { get; set; }
    }
}
