//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PROIVEntities : DbContext
    {
        public PROIVEntities()
            : base("name=PROIVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CATEGORIA> CATEGORIAS { get; set; }
        public virtual DbSet<ESTADO_MESAS> ESTADO_MESAS { get; set; }
        public virtual DbSet<EXTRA> EXTRAS { get; set; }
        public virtual DbSet<FACTURA> FACTURAS { get; set; }
        public virtual DbSet<MESA> MESAS { get; set; }
        public virtual DbSet<MESERO> MESEROS { get; set; }
        public virtual DbSet<PRODUCTO> PRODUCTOS { get; set; }
        public virtual DbSet<PRODUCTO_X_ORDEN> PRODUCTO_X_ORDEN { get; set; }
        public virtual DbSet<ORDENE> ORDENES { get; set; }
    }
}
