//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PROIVEntities : DbContext
    {
        public PROIVEntities()
            : base("name=PROIVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CATEGORIA> CATEGORIAS { get; set; }
        public virtual DbSet<ESTADO_MESAS> ESTADO_MESAS { get; set; }
        public virtual DbSet<EXTRA> EXTRAS { get; set; }
        public virtual DbSet<FACTURA> FACTURAS { get; set; }
        public virtual DbSet<MESA> MESAS { get; set; }
        public virtual DbSet<MESERO> MESEROS { get; set; }
        public virtual DbSet<ORDENE> ORDENES { get; set; }
        public virtual DbSet<PRODUCTO> PRODUCTOS { get; set; }
        public virtual DbSet<PRODUCTO_X_ORDEN> PRODUCTO_X_ORDEN { get; set; }
    }
}
